#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 25 17:27:50 2020
@author: Frederic Labbe
Extracting the best tree from the results generated by BPP.
usage: python ExtrBestTree.py
"""

import re
import glob

def ExtrBestTree():
    f = open("bestrees.out", 'w')
    files = glob.glob('*.out')
    for file in files:        
        with open(file, 'r') as bpp:
            for line in bpp:
                if line.startswith('(A)'):
                    info = next(bpp, '').strip()
                    tree = re.search(r"\(.+\;", str(info))
                    f.write('{}\n'.format(tree.group(0)))
    f.close()

if __name__ == '__main__':
    ExtrBestTree()
    