#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 25 17:27:50 2020
@author: Frederic Labbe
Extracting the best trees and their coordinates from the results generated by the A01 analysis of BPP.
usage: python ExtrBestTree.py
"""

import re
import glob

def ExtrBestTree():
    f = open("bestrees.out", 'w')
    g = open("bestrees_coord.out", 'w')
    g.write('Start\tStop\n'.format())
    files = glob.glob('*.out')
    for file in files:        
        with open(file, 'r') as bpp:
            if not bpp.name.startswith('bestrees'):
                coord = re.findall(r"[0-9]+", str(bpp.name))
                g.write('{}\t{}\n'.format(coord[0], coord[1]))            
            for line in bpp:
                if line.startswith('(A)'):
                    info = next(bpp, '').strip()
                    tree = re.search(r"\(.+\;", str(info))
                    f.write('{}\n'.format(tree.group(0)))
    g.close()
    f.close()

if __name__ == '__main__':
    ExtrBestTree()
    