###########################################################################################################
# Script: Define helpful functions to plot some standard population genomic statistics in sliding windows #
# Author: Frederic Labbe                                                                                  #
# Date: 12/02/2020                                                                                        #
# Affiliations: University of Notre Dame & University of Groningen                                        #
###########################################################################################################


################################################################
# Extract windows having outlier population genomic statistics #

# This function extracts the windows having outlier population genomic statistics (higher than the 97.5% quantile).
# data: the file containing the results generated by the script popgenWindows.py.
# stat: the statistic to be considered in the calculations, i.e. "pi", "dxy", or "Fst".
# species: the species to be considered in the calculations, e.g. "Species1", "Species2", or "Species1_Species2".
ExtOutStat <- function(data, stat, species) {
  x <- as.numeric(quantile(as.numeric(eval(parse(text = paste ("data$", stat, "_", species, sep = "")))), 0.975, na.rm = T)) #
  y <- subset(data, as.numeric(eval(parse(text = paste (stat, "_", species, sep = "")))) > x)                                # Subset windows having pi higher than the 97.5% quantile.
  return(y)
}
#TEST1 <- ExtOutStat(x, "dxy", "Species1_Species2")
#head(TEST1)
#TEST2 <- ExtOutStat(x, "Fst", "Species1_Species2")
#head(TEST2)
#TEST3 <- ExtOutStat(x, "pi", "Species1")
#head(TEST3)

############################################################
# Plot the population genomic statistics across the genome #

# This function plots the population genomic statistics across the genome and their lower and upper 2.5% quantiles.
# data: the file containing the results generated by the script popgenWindows.py.
# stat: the statistic to be considered in the calculations, i.e. "pi", "dxy", or "Fst".
# species: the species to be considered in the calculations, e.g. "Species1", "Species2", or "Species1_Species2".
# format: format of the plot, i.e. "col" (one column per scaffold), or "row" (one row per scaffold).
PlotStatWind <- function(data, stat, species, format) {
  x <- as.numeric(quantile(as.numeric(eval(parse(text = paste ("data$", stat, "_", species, sep = "")))), 0.025, na.rm = T))
  y <- as.numeric(quantile(as.numeric(eval(parse(text = paste ("data$", stat, "_", species, sep = "")))), 0.975, na.rm = T))
  if (format == "col") {
    z <- ggplot(data = data, aes(x = mid, y = as.numeric(eval(parse(text = paste(stat, "_", species, sep = "")))))) + # Standard population genomic statistics in sliding windows.
      geom_line() +                                                                                                   # Add a line.
      facet_grid(. ~ scaffold) +                                                                                      # Split the plot according to the scaffolds.
      geom_hline(yintercept = x, color = "blue", linetype = "dotted") +                                               # Add an horizontal lines showing the 2.5% quantile.
      geom_hline(yintercept = y, color = "red", linetype = "dotted") +                                                # Add an horizontal lines showing the 97.5% quantile.
      xlab("Chromosome position (bp)") +                                                                              # Change the name of the x axis.
      ylab(stat) +                                                                                                    # Change the name of the y axis.
      theme_bw(base_family = "") +                                                                                    # Removed the grey base.
      #scale_y_continuous(limits = c(0, 1)) +                                                                         # Change y axis limits.
      theme(axis.text = element_text(color = "Black"), 
            axis.title = element_text(color = "Black"), 
            axis.title.y = element_text(hjust = 0.5), 
            legend.title = element_blank())                                                                           # Remove the legend title and change color of the axis labels.
  } else {
    z <- ggplot(data = data, aes(x = mid, y = as.numeric(eval(parse(text = paste(stat, "_", species, sep = "")))))) + # Standard population genomic statistics in sliding windows.
      geom_line() +                                                                                                   # Add a line.
      facet_grid(scaffold ~ .) +                                                                                      # Split the plot according to the scaffolds.
      geom_hline(yintercept = x, color = "blue", linetype = "dotted") +                                               # Add an horizontal lines showing the 2.5% quantile.
      geom_hline(yintercept = y, color = "red", linetype = "dotted") +                                                # Add an horizontal lines showing the 97.5% quantile.
      xlab("Chromosome position (bp)") +                                                                              # Change the name of the x axis.
      ylab(stat) +                                                                                                    # Change the name of the y axis.
      theme_bw(base_family = "") +                                                                                    # Removed the grey base.
      #scale_y_continuous(limits = c(0, 1)) +                                                                         # Change y axis limits.
      theme(axis.text = element_text(color = "Black"), 
            axis.title = element_text(color = "Black"), 
            axis.title.y = element_text(hjust = 0.5), 
            legend.title = element_blank())                                                                           # Remove the legend title and change color of the axis labels.
  }
  return(z)
}

#TEST4 <- PlotStatWind(x, "pi", "Species1", "row")
#print(TEST4)
#TEST5 <- PlotStatWind(x, "dxy", "Species1_Species2", "col")
#print(TEST5)

